# This is a basic workflow to help you get started with Actions

name: Deploy to github pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-node@v2.1.2
        name: Configure node environment
      - uses: actions/checkout@v2
        name: Check out sources
      - name: Install dependencies
        run: npm install
      - name: Compile website
        run: npm run build
      - name: Deploy website
        run: |
          cd dist
          git init
          git config user.name "Willem Meints"
          git config user.email ""
          git add -A
          git commit -m 'Update website'
          git push -f https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/wmeints/practical-tensorflow-guide.git
          cd -
